### ISSUE TITLE
UDP network connection from PhhTrebleApp

### ISSUE THREAD

**Issue by XopmoH97** [phhusson/treble_experimentations#1005]
![Screenshot_20191213-110945](https://user-images.githubusercontent.com/51299245/70788433-8b26d080-1d99-11ea-9504-90c6fcc5812f.png)
Why does PhhhTrebleApp create this Internet connection to 67 UDP my router port?

**Comment by phhusson** [comment]
Considering ip destination and port source/destination, this is just a DHCP request/renewal.
This sounds like a bug of your app really, because Treble app doesn't do any DHCP request, this is done by framework.
However, treble app shares its UID with framework, so that's the probably the reason why your app thinks it's treble app.
