### ISSUE TITLE
GSI Rom: Google Play System Update

### ISSUE THREAD

**Issue by wolf3dryan** [phhusson/treble_experimentations#1200]
Hi.
First time leaving an issue.  The google play system update installs ok, but when you reboot your device on a gsi rom the update disappears and the default google play system update that came with the rom is still there.  Please fix this in your rom as it is the best gsi rom out there in the web.  So please let the google play system update survive the reboot process of the android operating system.

Thank you.

wolf3dryan

**Comment by phhusson** [comment]
Hello,

For various reasons, it's simply not possible to use Google Play System Update in my GSI.
For instance, I need this: https://android-review.googlesource.com/c/platform/bionic/+/1120324
And Google doesn't want to merge it.

The issue here is that you received those updates at all.
I'll try to check why you received it and disable it.

**Comment by phhusson** [comment]
Oh also I have to add that Google Play System Updates is useless with my GSIs as long as I keep updating Security Patches, because GPSU are released after monthly security patches.
