### ISSUE TITLE
Backup and Restore apps fail on Android 10 GSI with it's root system.

### ISSUE THREAD

**Issue by fourofspades** [phhusson/treble_experimentations#1214]
SwiftBackup fails to restore any application, regardless of it it's APK or Split APK
Titanium hangs (but carries on if you install APK manually) when it comes across Split APKs.

Other root solutions work correctly, Titanium isn't suppored anymore, and Swift Backup blame the root solution in the GSI, and say "just use Magisk, it works...".

here is the error code from Swift Backup, which may (or may not) help:

29/03/2020 12:32:44.085/AppRestoreTask: <Error: failed to write; fstat failed: EACCES (Permission denied),Failure [INSTALL_PARSE_FAILED_NOT_APK: Failed to parse /data/app/vmdl696138929.tmp/base]>
29/03/2020 12:32:44.100/AppRestoreManager: Performing post-restore tasks
29/03/2020 12:32:44.525/TaskService: Complete
29/03/2020 12:32:44.528/TaskNotificationHelper: <1 app(s) failed to restore

**Comment by phhusson** [comment]
In my opinion, if they tell you to handle that yourself, you shouldn't paying for their solution.
Also, the behaviour of their app is extremely shitty. I would almost say malware-ish.. It opens 4 SU connections without needing it, and does a lot of shit on it.

Looking at a strace, the command that fails is:
`cat /storage/emulated/0/SwiftBackup/accounts/xxx/yyy/.....app | pm install-write -S $APK_SIZE SESSION base`

This is honestly ridiculous, and shows they don't know what they're doing.
they should be doing `pm install-write ... /data/media/0/SwiftBackup/....` and things would just work smoothly

But since they don't know much about Android, they used /storage/emulated, which system_server isn't allowed to access.
But hey, they tricked the system by using a cat and a pipe instead, so the issue is about reading from a phhsu_daemon pipe, so that's something actually wrong on my side too.

Way to reproduce this issue:
`cd /storage/emulated/0; cat base.apk | pm install -S $(stat -c '%s' base.apk) -- -`

Way to circumvent the issue:
`echo '(allow system_server phhsu_daemon (fifo_file (getattr)))' >> /system/etc/selinux/plat_sepolicy.cil`

Also I commited an untested fix  (though i'm pretty confident about it)

**Comment by fourofspades** [comment]
I got a full refund :-) they were fine about it, but yes, the "support" response was very self righteous, it wasn't a problem with their product, someone elses problem...

**Comment by fourofspades** [comment]
Tested the change and restore of APK now works correctly. Thanks for looking into this. Being able to backup and restore data quickly and reliably allows me to switch to newer builds and try out other fixes and such.

**Comment by fourofspades** [comment]
Confirmed working in v215
