### ISSUE TITLE
Xiaomi Redmi Note 4 [Mido] Issue

### ISSUE THREAD

**Issue by nuelfrans** [phhusson/treble_experimentations#152]
Hi, i want to tell about issue i already found currently
- Hotspot can't be turned on
- Fingerprint sensor not detected
- VoLTE maybe because i don't use VoLTE so i don't know 
- Camera Apps don't work but when i use Open Camera it's work but the image quality is bad

Will be added later after exploring few thing, thanks

**Comment by Shadowghost** [comment]
Thanks for filing them on GitHub.
The issues are know and worked on. Hotspot isn't working on most devices right now. Fingerprint service crashes on mido for unknown reason, I already took logs for the dev. VoLTE is picky on AOSP and never worked for us without patches to the system (which will not happen here, since it's generic), but maybe there will be some workaround in the future :)

Keep always in mind, that we have an unofficial treble implementation on mido and it's not the main goal of this GSIs to work on unofficial, so our problems do have low priority.

**Comment by Elang-SBP** [comment]
Thanks for information, i new in this GSI works so i don't know much about them but i try to give a feedback to help the Dev
