### ISSUE TITLE
No more Arm32 64bit binder a-only build?

### ISSUE THREAD

**Issue by roynatech2544** [phhusson/treble_experimentations#1719]
On android 10 gsi, including latest one, you have a64-aonly-xxx build. On android 11 gsi, there is only a64-ab-xxx. I read that my phone, Samsung Galaxy A6+ 2018 , needs a64-aonly-xxx to boot the gsi.
Several reasons I think why you removed this variant is:
1. On android 11 sources, you can't build that variant 
2. You didn't build one since it is pre-release
I'll wait for your answer, thank you

**Comment by phhusson** [comment]
The reason is that exclusively Samsung did arm32_binder64 devices, and they upgraded pretty much all of them to Android 10 vendor which comes with System-as-Root, hence use A/B variant.
That's the case of your device, you have android 10 upgrade. Upgrade your device to Android 10 vendor, then you'll be able to use ab gsi.

14 févr. 2021 17:34:08 roynatech2544 <notifications@github.com>:

> On android 10 gsi, including lastest one, you have a64-aonly-xxx build. On android 11 gsi, there is only a64-ab-xxx. I read that my phone, Samsung Galaxy A6+ 2018 , needs a64-aonly-xxx to boot the gsi.
> Several reasons I think why you removed this variant is:
> 
- * > On android 11 sources, you can't build that variant
- * > You didn't build one since it is pre-release

**Comment by roynatech2544** [comment]
Should I select vndklite or that doesn't matter?

**Comment by phhusson** [comment]
Yes you'll need vndklite variant
