### ISSUE TITLE
[Galaxy Tab S7+] 100-second platform watchdog bite issue (/dev/watchdog0).

### ISSUE THREAD

**Issue by lss4** [phhusson/treble_experimentations#1911]
At of the end of #1744 I'm able to get GSIs working on this device, but there's an unsolved problem.

With GSIs, there is a 100-second watchdog that does not get fed which triggers a system reboot. This can be manually worked around by issuing this command.

```
# echo 'V' > /dev/watchdog
```

There are several ways to get this command executed automatically (either on Magisk side or system side), to effectively work around this issue, but I don't know if there are any good ideas to avoid having to manually work this issue around?

I've already looked at issues #1511 and #1730 which described similar problems, and they seem to say that the issue needs to be fixed on the kernel side. Should point out that a non-securized official phh-AOSP (with `phh-su`) does not have this issue, but the issue resurfaces as soon as the device is securized.

Don't know if `phh-su` is taking care of it, as the unofficial GSIs I've tested (and intended to use) are all `bvN`-flavor ones (that doesn't actually come with `phh-su`) and they all exhibit the issue requiring the offending 100-sec watchdog to be manually disabled using the command above.

Magisk doesn't appear to take care of this offending watchdog, as the issue happens regardless of whether Magisk is installed or not (Android 10 vendor is required for using Magisk).

**Comment by phhusson** [comment]
/dev/watchdog is handled by watchdogd ( https://github.com/phhusson/platform_system_core/blob/master/watchdogd/watchdogd.cpp )

Issue usually on Samsung devices with any Safetynet-passer (magisk, my securize, ...), is /dev/watchdog1, which is a secondary watchdog. watchdog1 is disabled by Samsung vendor automatically when bootloader is orange state. Hence it doesn't work if you cheat Safetynet.

Either way, nowadays, I disable watchdog1 anyway: https://github.com/phhusson/device_phh_treble/blob/android-11.0/rw-system.sh#L933 . This is NOT related to my SU, and works even without it.

So on my AOSP v309, there shouldn't be any issue with watchdog.

Now, you're saying you have issue with the first watchdog, which is handled by AOSP's watchdogd. I'm very surprised, but let's assume this is true, the fix IS NOT to disable this watchdog. Having one watchdog is good. (not that Android's watchdog is really amongst the most useful, since it doesn't check framework status or anything)

So, let's actually fix it, rather than disabling it.
For that, I'll need logs.

**Comment by lss4** [comment]
> /dev/watchdog is handled by watchdogd ( https://github.com/phhusson/platform_system_core/blob/master/watchdogd/watchdogd.cpp )
> 
> Issue usually on Samsung devices with any Safetynet-passer (magisk, my securize, ...), is /dev/watchdog1, which is a secondary watchdog. watchdog1 is disabled by Samsung vendor automatically when bootloader is orange state. Hence it doesn't work if you cheat Safetynet.
> 
> Either way, nowadays, I disable watchdog1 anyway: https://github.com/phhusson/device_phh_treble/blob/android-11.0/rw-system.sh#L933 . This is NOT related to my SU, and works even without it.
> 
> So on my AOSP v309, there shouldn't be any issue with watchdog.
> 
> Now, you're saying you have issue with the first watchdog, which is handled by AOSP's watchdogd. I'm very surprised, but let's assume this is true, the fix IS NOT to disable this watchdog. Having one watchdog is good. (not that Android's watchdog is really amongst the most useful, since it doesn't check framework status or anything)
> 
> So, let's actually fix it, rather than disabling it.
> For that, I'll need logs.

Actually I have three entries in `/dev` that are called watchdog.
```
/dev/watchdog
/dev/watchdog0
/dev/watchdog1
```

Haven't tried v309 yet. I tested v308 and that worked fine before securize, but the issue reappears after securize.

After some testing it seems I really need to disable `/dev/watchdog0`. The watchdog you mentioned, `/dev/watchdog1`, is not the problem.

Here's a freshly taken `last_kmsg` from the GSI I've been using ([Project Sakura](https://sourceforge.net/projects/braiagsi/files/Project-Sakura/May/) by braiagsi).

[last_kmsg0.gz](https://github.com/phhusson/treble_experimentations/files/6681456/last_kmsg0.gz)

**Comment by lss4** [comment]
A little update. With [DragKernel](https://github.com/b1ad3runn3r/drag-kernel-t975/) and the July build of OctaviOS, there's only one watchdog `/dev/watchdog1` which is being correctly fed. The offending `watchdog0` is not there.

I still need some further testing. I flashed it from TWRP and the original kernel image was patched with Magisk 23001, though I don't think whether the kernel image is Magisk patched or not matters here.

**Comment by lss4** [comment]
Closing this issue as I've effectively worked it around. I think the kernel needs to have `CONFIG_SOFT_WATCHDOG` unset or disabled to remove this offending watchdog (which [DragKernel](https://github.com/b1ad3runn3r/drag-kernel-t975/) did).

Though I think the GSI can actually try disabling all watchdogs present in the system as early as possible if none has real meanings in such contexts and would only cause trouble (like this one).
