### ISSUE TITLE
High pitched voices over VoIP

### ISSUE THREAD

**Issue by Hi1307** [phhusson/treble_experimentations#2082]
All VoIP calls distort incoming audio such that everyone on the call sounds like a chipmunk.

Microphone audio is ok as the other party can hear me normally.

Only affects VoIP. Calls made using IMS are normal.

Device: Mi 11 Lite 5G (renoir) (Qualcomm SM7350-AB Snapdragon 780G)
Version: 11.0 v313

**Comment by phhusson** [comment]
Why did you close this?

**Comment by boon1987** [comment]
Device: Lenovo Legion Y700 Wifi only version (Qualcomm 870)
Version: Android 12L Phusson v414

1.0 Hi, I encountered the same issue when using the Microsoft team. The VoIP incoming call voice is distorted like a chipmunk (fast speaking speed and robot voice). It happens 9 out of 10 times when I take the VoIP calls, and only appears normal in the remaining 1 time. The issue appears when I choose device mode, speaker mode, or headset mode to take the call. However, there is no distortion when I am use Bluetooth for the call.

2.0 The microphone is ok as the other party can hear me normally in all modes.

3.0 Strange enough, the VoIP call using Whatsapp behaves normally without any issue. I also don't have issue when playing other media apps like youtube, firefox browser, etc.

4.0 Note that I am facing same issue in the following Phh-treble-based ROM as well: SparkOS12.4,  CrDroid, Caos11 (android 11), etc.

I hope this issue can be fixed as all others features because I want to replace my Ipad with the Android table for my work.

Thank you.

**Comment by boon1987** [comment]
I see, thank for the fast reply. I had checked the setting called alternate audio policy but the issue still persists.

**Comment by boon1987** [comment]
> > Why did you close this?
> 
> Hello, sorry for the late reply, the initial reply got to my spam sweat_smile
> 
> Anyway, the fix for me was to use the alternate audio policy in the GSI settings. @boon1987 you might want to try that out.

By the way, have you used the Microsoft team app on your android for the team meeting VoIP call with the Phh treble ROM? Does it work perfectly?
