### ISSUE TITLE
AOSP 12.0 v400.c: "/system/bin/oplus-alert-slider" Using CPU Usage

### ISSUE THREAD

**Issue by CHECK-1234** [phhusson/treble_experimentations#2085]
I disabled all the a75 cores on a sdm845 device and I set the a55 cores to powersave governor and went to check to see what processes was using the CPU. 

In termux, I install the packages "tsu" and "htop". I then use the "tsu" command and then I used the "htop" command. Then I noticed that the process "/system/bin/oplus-alert-slider" 's CPU Usage was spiking up and then going down.

To fix this I moved "/system/bin/oplus-alert-slider" to "/system/oplus-alert-slider" so that the service "oplus-alert-slider" would not start.

I am not on a One Plus device.

**Comment by phhusson** [comment]
Right. Fixed in
https://github.com/phhusson/device_phh_treble/commit/2fa02fbf1704c1fff00f1f5833210197ce352189

It shouldn't have hurt much, it was just doing a fork() exec() every 5s, it
would appear as a spike only because of very low CPU frequency

FYI "oplus" (not sure how many upper cases there should be) isn't OnePlus,
it's BKK the company of Oppo, Realme and OnePlus (though yeah I guess
OnePlus are the only oplus device with an alert slider)

Le ven. 26 nov. 2021 à 16:30, CHECK-1234 ***@***.***> a
écrit :
