### ISSUE TITLE
[Galaxy j4 core(j4corelte)] rom not recognizing SIM CARD

### ISSUE THREAD

**Issue by Luizin5** [phhusson/treble_experimentations#2139]
Hello, I'm trying to use sim card in my j4 core, but it was not possible because none of gsi recognize my SIM CARD.

I tested /e/ with android pie, havoc os pie and aosp pie. None recognized SIM card

help me, please.

Goodbye from brazil

**Comment by zainullahk** [comment]
if you have dual sim switch to second sim

**Comment by nation888** [comment]
Be sure to be aware of where the sim card is correctly positioned. I’ve never seen a dual sim on a galaxy j4. Have you tried the Phh extras in settings? Try IMS ? Can you make phone calls but have to internet? Regards, Trevor W. From: Luizin5Sent: January 11, 2022 10:05 AMTo: phhusson/treble_experimentationsCc: SubscribedSubject: [phhusson/treble_experimentations] [Galaxy j4 core(j4corelte)] rom not recognizing SIM CARD (Issue #2139) Hello, I'm trying to use sim card in my j4 core, but it was not possible because none of gsi recognize my SIM CARD.I tested /e/ with android pie, havoc os pie and aosp pie. Anyone recognized SIM cardhelp me, please.Goodbye from brazil—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by Luizin5** [comment]
> 

my device is j4 core, with dual SIM.
i resolved this issue just switching to the second SIM.
thanks
