### ISSUE TITLE
[MTK 6739/LAVA Iris 65] FAILED (remote: 'sparse image size span overflow.') when fastboot flash system system.img

### ISSUE THREAD

**Issue by tasnimtamim** [phhusson/treble_experimentations#2141]
Trying to install AOSP 8.1. Whenever I try to flash the img file using fastboot, I get this error:
```
C:\aa\platform-tools_r31.0.3-windows\platform-tools>fastboot flash system system.img
Sending sparse 'system' 1/7 (131068 KB)            OKAY [  5.172s]
Writing 'system'                                   FAILED (remote: 'sparse image size span overflow.')
fastboot: error: Command failed
```
Also tried flashing using SP Flash Tool but get similar error message, error status_too_large.
Here's TWRP Screenshot of system partition.
![Screenshot_2009-12-31-18-01-23](https://user-images.githubusercontent.com/52713990/149338703-da068e11-4975-4072-b8dd-1a50c01ed2a6.jpg)

and the size of the system.img
![explorer_gaQMVvstb7](https://user-images.githubusercontent.com/52713990/149338861-462f166e-96d7-4a4c-876f-bf3006e162e2.png)

Any help will be greatly appreciated, as I'm in great need of a AOSP ROM for my device. Thanks

**Comment by KatoTempest** [comment]
Can't flash from twrp?

**Comment by tasnimtamim** [comment]
> Can't flash from twrp?

My version of TWRP does not have the option to flash system. Only boot and recovery.

**Comment by nation888** [comment]
When installing are you selecting IMG? (bottom right button says ZIP) select to change ZIP to IMG. Then be sure to select system partition. Regards, Trevor W. From: Tasnim TamimSent: January 14, 2022 2:15 AMTo: phhusson/treble_experimentationsCc: SubscribedSubject: Re: [phhusson/treble_experimentations] [MTK 6739/LAVA Iris 65] FAILED (remote: 'sparse image size span overflow.') when fastboot flash system system.img (Issue #2141) Can't flash from twrp?My version of TWRP does not have the option to flash system. Only boot and recovery.—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by tasnimtamim** [comment]
> When installing are you selecting IMG? (bottom right button says ZIP) select to change ZIP to IMG. Then be sure to select system partition. Regards, Trevor W
These are the options I get:
![Screenshot_2022-01-14-05-32-29](https://user-images.githubusercontent.com/52713990/149510306-c2952c81-7c8c-4e23-ad4c-2831b8cafc56.png)

My TWRP version (this is the only availabe version for my device):
![Screenshot_2022-01-14-05-32-32](https://user-images.githubusercontent.com/52713990/149510340-eac27fd3-3435-4665-91e9-50994de9ab50.png)

**Comment by KatoTempest** [comment]
do you have the device tree of the twrp of your device? you can add the system flashing from the fstab, if you have or find the device tree maybe it can help you

**Comment by tasnimtamim** [comment]
> do you have the device tree of the twrp of your device? you can add the system flashing from the fstab, if you have or find the device tree maybe it can help you

Sorry, not sure about the device tree. Not too knowledgeable about that. Here's the github link I got my TWRP from though:
https://github.com/TwrpBuilderTests/android_device_lava_iris65

**Comment by phhusson** [comment]
Why do you think having a twrp would help?
As far as I understand the issue is that the system partition is simply too small, having a twrp wouldn't change that, would it?

**Comment by KatoTempest** [comment]
In part it will not help to increase the size of the system, but it is to enable the flashing of the system since apparently it can only modify boot and vendor, also to update the twrp of this guy, so it will be more compatible with gsi based on android 12 in case the device allows installation

**Comment by tasnimtamim** [comment]
Soooo... what can I do here? Find somehow to increase system partition or other things I can do?

**Comment by nation888** [comment]
Change the recovery and vbmeta to https://mega.nz/folder/5aBlACxY#5C6EDxBQmyQ5K76UhmpQ9g My Oukitel K9 should be the same, MTK6765 file structure, these work using spflash tool.Regards, Trevor W. From: Tasnim TamimSent: January 14, 2022 5:44 AMTo: phhusson/treble_experimentationsCc: nation888; CommentSubject: Re: [phhusson/treble_experimentations] [MTK 6739/LAVA Iris 65] FAILED (remote: 'sparse image size span overflow.') when fastboot flash system system.img (Issue #2141) When installing are you selecting IMG? (bottom right button says ZIP) select to change ZIP to IMG. Then be sure to select system partition. Regards, Trevor WThese are the options I get:My TWRP version (this is the only availabe version for my device):—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.Message ID: ***@***.***>

**Comment by tasnimtamim** [comment]
Is the recovery file correct? It's 32mb, which is largest I've ever seen for a recovery file. Anyhow on SP Flash Tool I get this error message: 
![image](https://user-images.githubusercontent.com/52713990/149770186-f58a8eac-eff7-4faa-a6a7-1f2746ff3f53.png)

Fastboot and TWRP is same story: 
`C:\lava\platform-tools_r31.0.3-windows\platform-tools>fastboot flash recovery "C:\lava\Archive-1a03\Shared folder\recovery.img"
Sending 'recovery' (32768 KB)                      OKAY [  9.700s]
Writing 'recovery'                                 FAILED (remote: 'size too large')
fastboot: error: Command failed

C:\lava\platform-tools_r31.0.3-windows\platform-tools>`
TWRP shows this:  "size of image is larger than target device"
> Change the recovery and vbmeta to https://mega.nz/folder/5aBlACxY#5C6EDxBQmyQ5K76UhmpQ9g My Oukitel K9 should be the same, MTK6765 file structure, these work using spflash tool.Regards, Trevor W. From: Tasnim TamimSent: January 14, 2022 5:44 AMTo: phhusson/treble_experimentationsCc: nation888; CommentSubject: Re: [phhusson/treble_experimentations] [MTK 6739/LAVA Iris 65] FAILED (remote: 'sparse image size span overflow.') when fastboot flash system system.img (Issue #2141) When installing are you selecting IMG? (bottom right button says ZIP) select to change ZIP to IMG. Then be sure to select system partition. Regards, Trevor WThese are the options I get:My TWRP version (this is the only availabe version for my device):—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.Message ID: ***@***.***>
