### ISSUE TITLE
[AOSP9][Xiaomi Mi 5X][tiffany] Bluetooth is not working

### ISSUE THREAD

**Issue by vvorth** [phhusson/treble_experimentations#215]
Turning Bluetooth on lasts for about 1 minute and fails at the end.

Device: Xiaomi Mi 5X
Name: tiffany
boot and vendor partitions are from AOSP Extended 5.8 (Android 8.1)
GSI: v105 vanilla aonly nosu

[bluetooth_qs.log](https://github.com/phhusson/treble_experimentations/files/2418216/bluetooth_qs.log)
[getprop.txt](https://github.com/phhusson/treble_experimentations/files/2418373/getprop.txt)

**Comment by myfreeweb** [comment]
> lasts for about 1 minute and fails at the end

I've had a similar situation with Wi-Fi when Magisk-rooted, turned out to be a SELinux related issue: https://github.com/topjohnwu/Magisk/issues/552 — very similar appearance, trying to turn on and failing after some time. Looking through your log, doesn't look like SELinux denied any library loads or anything like that, mostly just `tmpfs` junk

**Comment by phhusson** [comment]
Dupe of #180
