### ISSUE TITLE
Unopenable OTG Error

### ISSUE THREAD

**Issue by AshFly6** [phhusson/treble_experimentations#2218]
Some phones running the aosp lost their otg function. Maybe adding a switch of "enabling otg connection" in "pph treble settings" could be considered.

**Comment by phhusson** [comment]
It's 100% device specific. Some devices already have an option to enable OTG.
But it must be done on a per-device basis.

**Comment by linlarr** [comment]
@AshFly6 this problem can be fixed by running in terminal
echo '1' > /sys/class/power_supply/usb/otg_switch
or at least it works on my device Oppo A15

though with AOSP you are very limited to which kind of fs your USB device can be.... NTFS doesn't work unless your kernel supports it (mine does thankfully)..... Fat32 works without issues though

P.S you can make a magisk module that runs that command automatically on startup

Proof
![Screenshot_20220307-092739](https://user-images.githubusercontent.com/101093447/156995100-d1998e8b-4249-40aa-b0fc-32a45db61945.png)
![Screenshot_20220307-092746_1](https://user-images.githubusercontent.com/101093447/156995246-9f88e71d-8589-4598-a695-a576974b5486.png)

**Comment by AshFly6** [comment]
> @AshFly6 this problem can be fixed by running in terminal echo '1' > /sys/class/power_supply/usb/otg_switch or at least it works on my device Oppo A15
> 
> though with AOSP you are very limited to which kind of fs your USB device can be.... NTFS doesn't work unless your kernel supports it (mine does thankfully)..... Fat32 works without issues though
> 
> P.S you can make a magisk module that runs that command automatically on startup
> 
> Proof ![Screenshot_20220307-092739](https://user-images.githubusercontent.com/101093447/156995100-d1998e8b-4249-40aa-b0fc-32a45db61945.png) ![Screenshot_20220307-092746_1_1](https://user-images.githubusercontent.com/101093447/156995737-abc64358-0e0c-4843-94b4-f86c1e3790be.png)

The code 
echo '1' > /sys/class/power_supply/usb/otg_switch
is efficient.
Helpful you!

**Comment by AshFly6** [comment]
> @AshFly6 this problem can be fixed by running in terminal echo '1' > /sys/class/power_supply/usb/otg_switch or at least it works on my device Oppo A15
> 
> though with AOSP you are very limited to which kind of fs your USB device can be.... NTFS doesn't work unless your kernel supports it (mine does thankfully)..... Fat32 works without issues though
> 
> P.S you can make a magisk module that runs that command automatically on startup
> 
> Proof ![Screenshot_20220307-092739](https://user-images.githubusercontent.com/101093447/156995100-d1998e8b-4249-40aa-b0fc-32a45db61945.png) ![Screenshot_20220307-092746_1_1](https://user-images.githubusercontent.com/101093447/156995737-abc64358-0e0c-4843-94b4-f86c1e3790be.png)

Anyway the code also works on my device realme Q3 5G. You are great help.

**Comment by AshFly6** [comment]
I don't close the issue so that more devices' solutions could be provided here.
