### ISSUE TITLE
[Xiaomi Mi 6X] stuck on booting animation (bootloop)

### ISSUE THREAD

**Issue by suwakowww** [phhusson/treble_experimentations#307]
I don't know it's similar #281 or not.
I exchanged a Mi 6X (wayne) device from others, and it have MIUI v10.0.2.0 (China stable) ROM. (anti=4)
When I flash AOSP 9.0 v107 (gapps+su), when I performed a clean flash (starts from unlock phone), it will stuck on booting animation.
the last 5 lines log here:
````
07-04 04:45:11.757  1413  1413 F linker  : CANNOT LINK EXECUTABLE "/vendor/bin/hw/vendor.qti.hardware.factory@1.0-service": library "vendor.qti.hardware.factory@1.0.so" not found
07-04 04:45:16.758  1414  1414 F linker  : CANNOT LINK EXECUTABLE "/vendor/bin/hw/vendor.qti.hardware.factory@1.0-service": library "vendor.qti.hardware.factory@1.0.so" not found
07-04 04:45:21.758  1415  1415 F linker  : CANNOT LINK EXECUTABLE "/vendor/bin/hw/vendor.qti.hardware.factory@1.0-service": library "vendor.qti.hardware.factory@1.0.so" not found
07-04 04:45:26.759  1416  1416 F linker  : CANNOT LINK EXECUTABLE 

"/vendor/bin/hw/vendor.qti.hardware.factory@1.0-service": library "vendor.qti.hardware.factory@1.0.so" not found
07-04 04:45:31.760  1417  1417 F linker  : CANNOT LINK EXECUTABLE "/vendor/bin/hw/vendor.qti.hardware.factory@1.0-service": library "vendor.qti.hardware.factory@1.0.so" not found

````
Full logs hers:
[bootfail-wayne2.log](https://github.com/phhusson/treble_experimentations/files/2643759/bootfail-wayne2.log)

But when I flash Magisk 17.3 after flashed GSI, it will boot normally.

**Comment by phhusson** [comment]
> 07-04 04:42:17.212   824  1073 E Cryptfs : Orig filesystem overlaps crypto footer region.  Cannot encrypt in place.

The way you formated is wrong. (I'd guess fastboot format? could also be a broken TWRP)
If in doubt, format with stock recovery.

**Comment by myfreeweb** [comment]
I've had the

```
07-04 04:45:21.758  1415  1415 F linker  : CANNOT LINK EXECUTABLE "/vendor/bin/hw/vendor.qti.hardware.factory@1.0-service": library "vendor.qti.hardware.factory@1.0.so" not found
```

endless bootanimation issue on my Mi A2 (jasmine) because I was upgrading from a really old LOS16 GSI that was (IIRC) hacked to use Oreo vendor images to a [current LOS16 GSI](https://forum.xda-developers.com/project-treble/trebleenabled-device-development/gsi-lineageos-16-0-gsi-arm64-ab-how-to-t3908029) that was expecting the proper Pie vendor image. Upgrading vendor solved the issue.

The issue OP was having

> when I flash Magisk 17.3 after flashed GSI, it will boot normally

is not this (also `MIUI v10.x` confirms it was Pie already), but for people googling the "qti.hardware.factory" string, this is one of the few results.
