### ISSUE TITLE
SafetyNet Pass / no SU build

### ISSUE THREAD

**Issue by kaiomatico** [phhusson/treble_experimentations#31]
Hi, first of all thanks for the awesome work!
Could you please provide builds without SU so these can pass SafetyNet? I can't unroot because there is no working TWRP Image for my device.

Best regards :)

**Comment by penn5** [comment]
Maybe install magisk manager and use the installed su to convert to magisk. Afaik magisk can do this.

**Comment by kaiomatico** [comment]
Thank you for the great idea, but as soon as I grant Magisk Manager the root permissions the app crashes and android asks me if I want to re-open the app.

**Comment by kaiomatico** [comment]
Closed because according to this post GSI's will never support SafetyNet :(
https://forum.xda-developers.com/showpost.php?p=76424596&postcount=1804

**Comment by weirdal3333** [comment]
UH, my phone completely passes safetynet with the vanilla GSI and magisk...

Please make a build release with gapps, but no su for both 8.1 and 9 versions.

**Comment by penn5** [comment]
When you pay for a faster build host he can. Until then, no go.
I'd suggest using a gapps addon

**Comment by weirdal3333** [comment]
I'm building it myself using the dakkar script. If I use the original boot.img before I flash the GSI without unlocking the bootloader, it passes safetynet. My case might be a special case because spflashtool works with and without unlocking via fastboot. I have a DoogeeS70 MT6367v (helio p23).

**Comment by penn5** [comment]
Yes, that's a special case. Your phone hasn't got a tripped secboot flag so you don't have to unlock it. Most phones need bootloader unlock to boot a gsi. To pass with an unlocked bl, you'd have to spoof it as locked to Android.

**Comment by weirdal3333** [comment]
NICE! So if I build a GSI without su, and use Magisk, it should work? I'm giddily happy now. I hope that there comes a time where GSIs can get OTA updates so I don't have to build the entire image each time ^_^

**Comment by weirdal3333** [comment]
Hey, just a thought, but why is @phhusson including su by default? Magisk is probably a better option because it's optional. 
It might reduce the build-time and resources if he removed it from all of the builds, and more devices would have a chance of passing safetynet. Is he purposely trying to fail safetynet?
After a bit of testing and research, I've found that you can relock the bootloader after flashing on lots of MTK devices, and Magisk is compatible with the ones I tested.

**Comment by phhusson** [comment]
Lol, what would be the purpose of failing safety net?
And do you really think removing a file is a very high barrier of entry?

why do I include my own su?
- it's much easier to install than magisk
- it doesn't break random things spuriously
- it works where magisk doesn't work

My su is optional. Though at build-time. Feel free to build your own
version without it, it's opensource.
Hell I even give super easy shell scripts to do it!
(And the time lost in build to include it is under one second, so uh...)

**Comment by weirdal3333** [comment]
That makes sense. 

In any case, installing the Magisk zip actually removes any pre-existing su, and allows the device to pass the important half of safetynet. If I really wanted to, I could then uninstall Magisk and that would remove root from the device. 

I've learned a whole bunch since my last comment, and I can see where you're coming from. Since safetynet actually tries to find a file called 'su', maybe you could include a script that you can run from recovery to remove root? I don't know if it's one file or not, but if it is maybe make a button that you have to tap 10 times at the bottom of developer options that removes root and reboots if the user *really* wants to do that 😁

Side note: setting up a device for older non-tech people needs root (I have to make certain apps persistent like TeamViewer for Android, the launcher, a WiFi password, and DNS settings, among other things because of accidental factory resets), but I don't want them accidentally deleting everything in `/system` somehow. It's happened before. I don't know how.
