### ISSUE TITLE
Pixel 2 GSI ROMS

### ISSUE THREAD

**Issue by Adamsapple1** [phhusson/treble_experimentations#359]
Hi I'm new to rooting so I will do my best to explain so bear with me here. 

So I want to install HavocOS 2.0 OFFICIAL on to my pixel 2. And it is a GSI so I followed the proper installation instructions like how you would for any other phone. I successfully flashed the GSI via fastboot and that was it. I tried to reboot my phone to try out the ROM but it tells me that there is a load error. I do not remember exactly what it said in the bootloader  but I did a bit of research and I found out that it has something to do with unofficial OEMs. I looked at Phhusson's list of supported Treble devices and I saw the pixel 2. When I clicked on it, it showed me this paragraph by Phhusson.

"on the Pixel 2 (walleye), the v15 system image (8.1) successfully boots over top of the OPM2.171019.029 factory image (8.1) after reflashing the vbmeta partition as follows:

$ fastboot --version
fastboot version 0.0.1-4500957
Installed as XXX
# extract vbmeta from the factory image zip and reflash:
$ fastboot --disable-verity flash vbmeta vbmeta.img

$ md5sum system-arm64-ab-vanilla-nosu.img
9aeacaa52a12feca8cb737b3fd083714  system-arm64-ab-vanilla-nosu.img
$ sha256sum system-arm64-ab-vanilla-nosu.img 
ec0e6299491dd8c6c9976e19fdfa887b470e9aaf4802632dd6295e7fb9cee38b  system-arm64-ab-vanilla-nosu.img
$ sha256sum walleye-opm2.171019.029-factory-41296266.zip 
4129626633cbab200c6c18fc52b2dd832714ef96761e1866b60d462e4dd39cac  walleye-opm2.171019.029-factory-41296266.zip"

Now like I said, I'm sort of new to rooting, even more new to GSIs. If anyone can translate what this means to me or give me a more in depth tutorial I would much appreciate it. :)

**Comment by jamuir** [comment]
The Pixel 2 is an AVB 1.0 device.  There are special partitions (vbmeta_a, vbmeta_b) on it that are used to verify the integrity of other partitions (e.g. system, boot, vendor, dtbo).

You need to disable the integrity check for the system image because you are replacing it with a GSI.  You can do that by updating the vbmeta partition.  If you don't do this, then when you try to boot the GSI, the device will quickly reboot into bootloader/fastboot mode.

This basic process is this:

1. put your unlocked Pixel 2 in fastboot mode and flash it with a factory image: https://developers.google.com/android/images

2. erase the vbmeta partition and flash it with a special vbmeta image that disables the AVB checks.  M. Rahman provides a link to such a vbmeta image in his article:  https://www.xda-developers.com/flash-generic-system-image-project-treble-device/

3. erase then flash the system partition with a GSI:
` fastboot erase system && fastboot flash system gsi-system.img`

4. wipe userdata and reboot:  `fastboot -w reboot`

The official documentation is here:  https://source.android.com/setup/build/gsi#flashing-gsis

**Comment by Adamsapple1** [comment]
Thank you for all the help! Successfully installed havoc os on my pixel 2.

**Comment by jamuir** [comment]
@Adamsapple1 :  glad that you are up and running now.

Could you close this issue?
