### ISSUE TITLE
[Moto E5] Sluggish animations

### ISSUE THREAD

**Issue by XavierWrz** [phhusson/treble_experimentations#382]
the rom is smooth, but the animations are a bit sluggish, the animation when going to recents, opening apps etc
tested in v109
[device_info.txt](https://github.com/phhusson/treble_experimentations/files/2808901/device_info.txt)
[dmesg.txt](https://github.com/phhusson/treble_experimentations/files/2808902/dmesg.txt)
[logcat.txt](https://github.com/phhusson/treble_experimentations/files/2808903/logcat.txt)

**Comment by phhusson** [comment]
Why did you close it?

Le mer. 30 janv. 2019 à 18:09, GripKrieger <notifications@github.com> a
écrit :

**Comment by GripKrieger** [comment]
Cuz I send the same issue now via telegram, but I will reopen

**Comment by GripKrieger** [comment]
i found a fix zip that fixes the animations,created for this gsi  now it's very smoother, i will leave the zip here for research, because i don't know what thing did and the phone now works like a charm!
[AOSP-lag-fix.zip](https://github.com/phhusson/treble_experimentations/files/2824057/AOSP-lag-fix.zip)
