### ISSUE TITLE
Ulefone Power 5 Mobile networks works only on first sim only 2G mode

### ISSUE THREAD

**Issue by jMurr** [phhusson/treble_experimentations#416]
Hi! I have Ulefone Power 5 on MTK 6763.
The phone can't connect to mobile network 3G or 4G, only 2G (EDGE) and only first sim-card.

**Comment by phhusson** [comment]
try that:
```
adb root
adb shell
$ sqlite3 /data/user_de/0/com.android.providers.telephony/databases/telephony.db 'update carriers set  modem_cognitive=1'
```

**Comment by jMurr** [comment]
Now both SIM cards connected to their networks on 4G/
But, the second SIM periodically looses network and network signal level is very low.
![screenshot_20190302-201818](https://user-images.githubusercontent.com/13546034/53685906-853f9180-3d29-11e9-8b07-530f6ae2c6b5.png)
![screenshot_20190302-201808](https://user-images.githubusercontent.com/13546034/53685905-853f9180-3d29-11e9-9be0-c0116431fa5a.png)

**Comment by stormwin** [comment]
Hi all,
I have my phone successfully running on AOSP 9 for almost a month.
Haven't tested SIM because it is not my primary phone (yet).
What i detected as a problem so far:
1. Camera button (hardware one) not starting camera app and not taking photo.
2. I have sound only on the right speaker. Nothing coming out from the left one.  It was working great on stock rom.
3. Sometimes when the phone is locked, and i click on power button, screen flashes ~5 times. (2-3 flashes per second)

Maybe these can be fixed with some build.prop line, i don't know.
@jMurr Can you confirm these problems on your end?

@phhusson

**Comment by phhusson** [comment]
Sounds like this issue is a big mess, but original issue has been fixed.
If you have nother issues, open new issues.
