### ISSUE TITLE
libc : Access denied finding property....

### ISSUE THREAD

**Issue by Reveran** [phhusson/treble_experimentations#429]
Hi, I took the treble partition of an A8 2018 and placed it in my A7 2017 replacing the files needed for it to boot, I know that is not optimal but it is what has given me the best results.

it seems that libc does not have access to the system properties and the java vm crashes.
I attach the values returned by getprop

```
03-09 16:11:25.930  2897  2897 I SystemServer: StartPackageManagerService
03-09 16:11:25.931  2897  2897 E libc    : Access denied finding property "pm.dexopt.first-boot"
03-09 16:11:25.931  2897  2897 E libc    : Access denied finding property "pm.dexopt.boot"
03-09 16:11:25.931  2897  2897 E libc    : Access denied finding property "pm.dexopt.install"
03-09 16:11:25.931  2897  2897 E libc    : Access denied finding property "pm.dexopt.bg-dexopt"
03-09 16:11:25.931  2897  2897 E libc    : Access denied finding property "pm.dexopt.ab-ota"
03-09 16:11:25.931  2897  2897 E libc    : Access denied finding property "pm.dexopt.inactive"
03-09 16:11:25.931  2897  2897 E libc    : Access denied finding property "pm.dexopt.shared"
03-09 16:11:25.931  2897  2897 E System  : ******************************************
03-09 16:11:25.932  2897  2897 E System  : ************ Failure starting system services

```
I can't find the missing symbol for the audio or the other one for the sensors (I think it's the least of it at the moment).

[logcat.txt](https://github.com/phhusson/treble_experimentations/files/2948687/logcat.txt)

[getprop.txt](https://github.com/phhusson/treble_experimentations/files/2948688/getprop.txt)

PD: I cleaned some adb related logs

**Comment by phhusson** [comment]
I'm closing thie issue since this isn't an issue of mine.

I prefer discussing treble porting on telegram or IRC, but we can stay here if you prefer.

For the properties issue, I'd say your SELinux policy is broken. Perhaps you're using static sepolicy (i.e. a /sepolicy in the boot.img) instead of using treblized sepolicy (using /{system,vendor}/etc/selinux/*.cil)

For the issue:
```
03-09 16:11:15.215  2551  2551 E HAL     : dlopen failed: cannot locate symbol "_ZN7android8hardware7sensors4V1_0eqERKNS2_10SensorInfoES5_" referenced by "/vendor/lib64/libsensorndkbridge.so"...
```
You should NOT have a vendor-sided sensorndkbridge, you really should use system's

For audio issue, I'm not too sure what's happening, but the missing symbol is in system's android.hardware.audio.common@2.0-util.so \
I guess you could patchelf android.hardware.audio@2.0-impl.so to add require to this lib
