### ISSUE TITLE
[Xiaomi Redmi 6a] Bootlooping. Can't able to boot system.

### ISSUE THREAD

**Issue by sridharkrishna** [phhusson/treble_experimentations#605]
Install lastest GSI on Redmi 6a (Cactus) but finally, it ends with a boot loop. It won't enter into the system.

**Comment by phhusson** [comment]
Some people did manage to boot it on this, so pleas give more details.

**Comment by lastant** [comment]
I had a similar issue on my Redmi 6 Pro. The first time it was because I was using a wrong build (ARM instead of ARM64 for my device). The second time because I didn't do the wipe properly: in the TWRP I was selecting Advanced wipe and then "Dalvik, Cache, System, Data", but there was a red error something like "/system partition could not be unmounted" and I would just ignore it. When I unmounted System myself and made sure (one by one) that all these partition could be successfully wiped (and the ROM image installed on the system partition afterwards), it worked.

**Comment by g4nym3de** [comment]
> Some people did manage to boot it on this, so pleas give more details. Le lun. 8 juil. 2019 à 06:20, Sridhar Ananthakrishnan < notifications@github.com> a écrit :
> […](#)

Steps performed:
Fastboot erase system
Fastboot flash -u system system-arm-aonly.img (tried arm 32 a only, arm32_binder64, and arm64, none of them worked.)
Fastboot -w reboot

Also did twrp advanced wipe before these procedures, no effect whatsoever. Prior to flashing I was using the latest MIUI 10 dev version.

Thanks for any feedback!

**Comment by lastant** [comment]
@g4nym3de If you had Android 8 Miui 10.3.6.0 and lower, you need to install ARM A-only. If you had Android 9 Miui 10.4.1.0 or Miui 9.8.1 or higher then you need to install ARM32-Binder64 AB(!). 

Also try to go to recovery, format data, wipe each partition individually (making sure there are no errors) and installing the firmware (from the recovery).
