### ISSUE TITLE
[Huawei PRA-LX1][AOSP 10 v202] Stuck in splash screen loop

### ISSUE THREAD

**Issue by rgcv** [phhusson/treble_experimentations#832]
Hello,

So, yeah, title pretty much succinctly explains the situtation. Might be related to #763. It might be worth mentioning that I flashed over AOSP 9 v119.

[dmesg.txt](https://github.com/phhusson/treble_experimentations/files/3800481/dmesg.txt)
[logcat.txt](https://github.com/phhusson/treble_experimentations/files/3800482/logcat.txt)

**UPDATE**: Reverting to flashing 9 v119 on top of it seems to be a safe fallback solution.

Whatever more information may be required, I'll be happy to ablidge and provide.

**Comment by man3l** [comment]
> Hello,
> 
> So, yeah, title pretty much succinctly explains the situtation. Might be related to #763. It might be worth mentioning that I flashed over AOSP 9 v119.
>

I have made a clean install by installing the v202 over stock rom (which i got from eRecovery) and everything seems to be fine except the camera app. Was even able to activate RCS on Messages. 
The Dialer app though displaying a message saying the device is not supported works just fine.
One app doesnt work (Playstation Remote Play) but thats because it detects root.

**Comment by rgcv** [comment]
> I have made a clean install

Damn.. I did *not* want to read that :disappointed: I might still go over the logs properly and see if I can find anything before I go ahead and restock the phone. Too much app data I'm not too fond of recovering nor backing up.

**Comment by rgcv** [comment]
Closing in favor of #1431
