### ISSUE TITLE
Treble Info disagrees with prop ro.build.ab_update

### ISSUE THREAD

**Issue by FintasticMan** [phhusson/treble_experimentations#835]
Hi,

I would like to know whether I should use a ROM with an ab partition scheme, or one with a only.  If I use the Treble Info app, it states I have an ab partition scheme, but I was sceptical because ota system updates still take a long time.  I then opened a terminal emulator and ran `getprop ro.build.ab_update` and it didn't give any response.  Other Treble checking apps say I do have Treble support but no ab partition scheme.  What do I do?

Thanks!

**Comment by phhusson** [comment]
Take A/B.

If you read carefully what Treble Info says, it says it's A-only, but that you should use A/B OS. Not that your system is A/B.

Treble Info has precisely been created to redirect users accurately.

For the technical details, speaking about GSI, A-only means system.img is /system, and A/B means system.img is /. This is because as of Oreo, A-only devices were using the first scheme, A/B the second one.
As of Pie (same for Q) all new devices are required to have system.img as / (what we call a/b). This doesn't apply to upgrading devices though.

**Comment by phhusson** [comment]
Please note that Treble info is opensource at https://github.com/penn5/TrebleCheck
Feel free to open issues or PR there if you think of a better wording

**Comment by FintasticMan** [comment]
Thanks, I will use an ab image!
