### ISSUE TITLE
Decryption fails on reboot

### ISSUE THREAD

**Issue by aosplink** [phhusson/treble_experimentations#868]
**GSI Used:** [v203 | system-quack-arm64-ab-gapps.img.xz](https://github.com/phhusson/treble_experimentations/releases/download/v203/system-quack-arm64-ab-gapps.img.xz)
**Devices tested on:** Redmi 7, Redmi Note 7, Redmi Note 7 Pro
#### What is happening?
When the GSI is installed for the first time (by flashing the system image), the device boots successfully and everything works. However, when the device is rebooted, a password is asked for and the password is said to be wrong even when the correct password is entered.
#### What do you think is the issue?
This is a very common issue indicating that the decryption failed on reboot.
#### Steps to reproduce
1. Download the GSI from the above link and extract the system image
2. Reboot into TWRP and flash the system image
3. Now wipe data, cache and dalvik
4. Reboot to system
5. Set up Android as you would normally do and add a screen lock (preferably a PIN for testing)
6. Reboot
7. You enter the password now, but you are told that you entered an incorrect password

**AOSP Version**: 10.0
**Commit hash:** https://github.com/phhusson/treble_experimentations/commit/c464983f9a8891a9c0326dd9a5821c3b987ff9d9

**Comment by aosplink** [comment]
Issue confirmed on GSI versions: [v203](https://github.com/phhusson/treble_experimentations/tree/v203)&nbsp;[v202](https://github.com/phhusson/treble_experimentations/tree/v202)

**Comment by phhusson** [comment]
ok please provide logcat on first and second boot

**Comment by darkestDark** [comment]
Your Problem is not gsi related. 
I have the same device and no problem there.

1) There is no Twrp which can handle the android 10 encryption, there is only one custom recovery which can (newest orangefox). 
2) Even if you use the newest orangefox the wipe doesnt work as expected. You are forced to format userdata completly because there are left fragments of old encryption. And in the moment you create a new locksettings.db in /data/system (by setting screen lock) you break the encryption.

Try it with format userdata completly...

**Comment by aosplink** [comment]
All right, the issue has been fixed. Disabling ForceEncrypt made the thing work
