### ISSUE TITLE
Build AOSP without su

### ISSUE THREAD

**Issue by EugW** [phhusson/treble_experimentations#918]
Because of SU included in your ROM SafetyNet (basicIntegrity) can't be passed, I tried many things: installing-uninstalling magisk, unSU script

**Comment by MCArTyR** [comment]
Try to install SafetyNet Module (form MagiskManager)

**Comment by EugW** [comment]
Already tried, nothing changed

**Comment by BenjamiNRM1** [comment]
I can't remember we're but found this

How to fix safetynet issues on phh's Q + msg on booting "there is problem in your device ..." : 

-Download UnSu.zip
-Download Termux (or use adb)
-Download magisk phh build ( tested with magisk.phh.v19.3 )

#####

-Flash magisk phh build
-In termux, enter:
su
(Grant permission on window)
for termux:
phh-su 0 /system/bin/phh-securize.sh
(Add adb shell if using adb)
-Reboot to twrp, mount /system.
-Flash UnSu.zip
-Factory reset with twrp. 
-Flash magisk phh build, reboot.

#####
For now BasicIntegrity should be fixed (true) + android's msg on booting should gone
#####

-In magisk repository (download section), install magisk hide props and BusyBox
-Reboot
-Install termux (or use adb), and run:
su
props
1
f
7
7
y
Reboot.

#######
CtsProfile should be fixed (true)
#######

Enjoy !

**Comment by man3l** [comment]
> I can't remember we're but found this
> 

> Enjoy !

It can be found [here](https://forum.xda-developers.com/p10-lite/how-to/gsis-manual-fixes-hi6250-devices-t3936745/post80847287&postcount=15)

**Comment by Temtaime** [comment]
Why closed?
AOSP still is shipped with su, that's awful

**Comment by phhusson** [comment]
How is that awful?

And you can disable it by pressing securize in treble settings

**Comment by Temtaime** [comment]
Hi. Thanks for a reply.
Because it forbids to pass safetynet and simple annoys because there's already magisk to flash.
Also after clicking Securize and answering Yes to "Remove root?" nothing happens for me. Supersu stays as it was even after reboot.

**Comment by phhusson** [comment]
> Because it forbids to pass safetynet

No it doesn't forbid to pass SafetyNet. Even without SU, my AOSP GSI won't
pass SafetyNet. Passing SafetyNet requires more stuff than just that (extra
stuff which are done by my "securize"), but it's ugly stuff and might break
features, hence it's not enabled by default.

> there's already magisk to flash.

Your sentence means there is some obligation to install magisk. I don't
understand why you're saying there is. The point of my SU is *precisely*
that most users *don't* need to flash magisk, because there is a SU
pre-integrated.
I personally don't use magisk on any of my 30+ devices running my AOSP GSI.
Most of them don't have custom recovery, so I wouldn't want to be bothered
with flashing magisk on it.

> Also after clicking Securize and answering Yes to "Remove root?" nothing
happens for me.

I'm happy to debug that, open a new issue for that.

> Supersu stays as it was even after reboot

If you have SuperSU (which has been obsolete for years now) installed, then
you have another issue. My ROM doesn't ship with SuperSU, but with
SuperUser.

**Comment by Temtaime** [comment]
De ma faute, SuperUser bien évidemment.
Je veux tout simplement passer SafetyNet afin d'utiliser GPay. Tous les articles que j'ai vus ont suggéré d'user Magisk Hide pour cela. Je doute que ce soit possible avec SuperUser.
Merci pour votre travail.
