### ISSUE TITLE
[Honor 8][AOSP 10 v205] Camera doesn't work

### ISSUE THREAD

**Issue by k10876** [phhusson/treble_experimentations#959]
Camera Issue
I have flashed stock Huawei Camera on the phone, and it failed to open.
I have recorded the log while the app crashed via `adb logcat`.
The log's below:
[logcat.txt](https://github.com/phhusson/treble_experimentations/files/3908077/logcat.txt

**Comment by k10876** [comment]
Another one:
In settings > Connected Devices, if you click `Connection preferences`, the app crashes.
This means that I cannot change NFC settings via settings.
Does that mean NFC isn't supported?

**Comment by henryg14class5** [comment]
Good day Senior Dev. I've also installed ASOP 10 V204 on Cubot_X18_Plus. It booted successfully however, camera is still an issue. The app does not show in app drawer. Flashlight toggle is locked permanently. After granting permissions of all sort, it still doesn't work. I've tried installing camera app from playstore and I get the message "failed to open camera. This may be in used by another application". I discovered that the settings app is also given permission to access camera and the permission cannot be revoked. Maybe that can be checked properly because on Android Pie, Settings app and SystemUI weren't given an expression permission to use camera. Perhaps, this should be checked on Android Quack. It could lead to making camera work on MediaTek devices.

**Comment by phhusson** [comment]
@henryg14class5 You're clearly at the wrong place.

**Comment by k10876** [comment]
@phhusson I have updated my phone to v205. but the camera doesn't work. I don't know why as the camera "has fixed".
"Swipe fingerprint for notifications" works on this version.

**Comment by phhusson** [comment]
@k10876 The release notes explicitely say it fixes *some* Huawei devices.

The issue is that this device isn't treble-compliant, so I won't support it.
You can find a workaround here:
https://github.com/phhusson/treble_experimentations/issues/614
It sadly doesn't work on Q GSI though

**Comment by k10876** [comment]
Yeah. On telegram, it says so.

**Comment by k10876** [comment]
Thanks a lot
